package test.se.monitor;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.nio.file.Paths;
import java.util.HashMap;
import java.util.Map;

public class _9NotificationTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        System.setProperty(
                "webdriver.chrome.driver",
                Paths.get("src/test/resources/chromedriver.exe").toString()
        );
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }


    @Test
    public void shouldRegister() throws InterruptedException {
        driver.get("https://dictionary.cambridge.org/");
        driver.manage().window().maximize();
        vars.put("window_handles", driver.getWindowHandles());
        driver.findElement(By.cssSelector(".lpl-0 > .tb")).click();
        Thread.sleep(4000);
        driver.switchTo().window(driver.getWindowHandles().toArray()[1].toString());
        driver.manage().window().maximize();
        Thread.sleep(1000);
        driver.findElement(By.cssSelector("#register-site-login > div:nth-child(1) > div > div > input"))
                .sendKeys("                  ");
        Thread.sleep(1000);
        driver.findElement(By.cssSelector("#names-row > div:nth-child(1) > div > input"))
                .sendKeys("");
        driver.findElement(By.cssSelector("#names-row > div:nth-child(2) > div > input"))
                .sendKeys("");
        driver.findElement(By.cssSelector("#password-row > div:nth-child(1) > div > input"))
                .sendKeys("          ");
        driver.findElement(By.cssSelector("#password-row > div:nth-child(2) > div > input"))
                .sendKeys("123456");
        driver.findElement(By.cssSelector("#subs-checkbox-cdo")).click();
        driver.findElement(By.cssSelector(" #gigya-checkbox-62954654473991340")).click();
        driver.findElement(By.cssSelector("#register-site-login > div.gigya-composite-control.gigya-composite-control-submit > input")).click();
        Thread.sleep(3000);
        System.out.println(vars);
        driver.findElement(By.cssSelector("#password-row > div:nth-child(1) > div > span"));
        driver.findElement(By.cssSelector("#register-site-login > div:nth-child(1) > div > div > span"));
        driver.findElement(By.cssSelector("#names-row > div:nth-child(1) > div > span"));
        driver.findElement(By.cssSelector("#names-row > div:nth-child(2) > div > span"));
    }
}
